### PR TITLE
[Older Version, Uses VSCodeManager] Implement Faster VS Code Manager

### PR DESCRIPTION
**Pull request by Tanner555**
I'm very close to finished. I've implemented a faster version of the visual studio code manager. This PR aims to speed up the generate modules process by not using visual studio to create the source files. It still uses visual studio to create the solution and project files.

### CODE REVIEW

**Comment by Tanner555** [comment]
Modules is finally compilable and the csproj file doesn't look too bad. It still takes a hit on performance, but it isn't nearly as bad as it was with the traditional visual studio approach. I'll try to clean up and optimize this PR later on.

**Comment by Tanner555** [comment]
Alright I've optimized the code manager so that File Reading and Writing doesn't take place very often. I also did some refactoring, and cleaned up old comments. Please test out this PR and see if it's up to your standards ;0

**Comment by Tanner555** [comment]
For some reason, visual studio doesn't want to open up after I created all the cs files. That is unless I reduce the visual studio delay. I don't really know how to use timers and async methods that well. I tried the best to make the process as smooth as possible.

**Comment by pixeltris** [comment]
This hybrid approach may come in useful later. For now #29 will do for manual file writing.

**Pull request closed without merging**
