### PR TITLE
Attempt upgrade to UE4-21

### PR DESCRIPTION
**Pull request by Tanner555**
Right now, I'm attempting to upgrade USharp to the new UE4.21. Luckily there doesn't seem to be a lot of errors when attempting to compile a 4.21 project. I'm considering commenting out most of the code that isn't compatible with the new version of ue4, but I did make some changes that'll hopefully work fine.

### CODE REVIEW

**Comment by Tanner555** [comment]
When you upgrade to 4.21, make sure you go into your project's managed folder, delete the .usharpGenerated and USharp.ProjectGeneratedVariables.props files, and reopen your project. You'll see some errors, but simply close the project and recompile the managed solution, then reopen your project.

**Comment by Tanner555** [comment]
I want to let users with ue4.20 be able to compile usharp with no issues. That would be nice if Unreal Engine 4 has a way to check the engine version at compile time, similar to Unity's preprocessor statements. We might be able to create an artificial preprocessor, one for 4.20 and another for 4.21. But without visual studio configurations, I have no idea how I would do that.

**Comment by Tanner555** [comment]
Users with version 4.20 should now be able to compile with these changes.

**Comment by pixeltris** [comment]
These changes have been adapted into https://github.com/pixeltris/USharp/commit/1a34d49fd7bef3a3a7dc40362ebeb3fed9fb7108. Thanks!

**Pull request closed without merging**
