### PR TITLE
Created Console Command That'll Generate Managed Solution

### PR DESCRIPTION
**Pull request by Tanner555**
I've added a command "USharpCreateManagedSolution" that'll generate a managed solution with all of the appropriate references and post build event wired up. I had to modify the gameSln and gameProj Settings fields so that the solution isn't cluttering up the Managed folder. There are some annoying bugs I've noticed, that may have to do with this PR. 

First of all, for some reason, a whole directory tree is created inside of the game solution's parent directory. For me, it kind of looks like this: 
`Extra Content Folder, inside My Projects, inside Unreal Projects, inside ProjectNormUE4 (My Proj Name), inside Managed, inside Binaries` 
Where the whole dir leading to this path is this: 
`E:\Extra Content Folder\My Projects\Unreal Projects\ProjectNormUE4\Managed`

-Edit: I temporarily Fixed the AssemblyRewriter bug that was caused by the TargetPath macro argument being null.

Second of all, for some reason, it doesn't seem like the AssemblyRewriter wants to do it's job. Obviously the path is right, because when the path is wrong, an error will be thrown and the build will fail. I've never had this issue before when I manually created the post build event. I don't think it's me putting the solution and project files inside the "Source" folder, which is inside of the "Managed" folder, that is causing this bug. When the rewriter works, UE4 hotreloads all the assemblies back into the gameengine. I can't find any of my mono classes inside the editor.

Please take a look at this PR and thoroughly test it out before merging it.

### CODE REVIEW

**Comment by Tanner555** [comment]
@RobertAcksel 
That's really funny! So you mean we both worked on the same feature, and you probably created a better version that I did? Well at least I learned something. Maybe we can help each other out. 😸

**Comment by RobertAcksel** [comment]
@Tanner555 
maybe yours is better. lets find out 😸. Lets discuss in gitter. Ill also commit the initial version i have so far. (still not the final one.)

**Comment by Tanner555** [comment]
Robert is currently working on a PR to implement the same feature. We'll see which one works the best.

**Comment by Tanner555** [comment]
Seems like Roberts PR works better than mine 😄 Well at least I learned a lot from trying to create this feature.

**Pull request closed without merging**
